version: '3'

services:
  db-postgres-evento:
    image: postgres:alpine
    ports:
      - ${POST_PORT}:5432
    container_name: "db-postgres-tiket"
    restart: always
    environment:
      - POSTGRES_USER=${POST_USER:-user}
      - POSTGRES_PASSWORD=${POST_PASSWORD:-123456}
